namespace GreenT.Settings.Data;

public enum BundleType
{
	MainManifest = 0,
	Media = 1,
	Items = 2,
	Shop = 3,
	EventShop = 4,
	CharactersData = 7,
	Tabs = 8,
	Fonts = 9,
	StarArt = 11,
	TaskArt = 12,
	MergeBalance = 13,
	Room = 14,
	Intrinsic = 15,
	Map = 16,
	VFX = 17,
	House = 18,
	Events = 19,
	PreloadedMap = 20,
	CharacterSkinAnimation = 21,
	CharacterSkinCard = 22,
	BattlePass = 23,
	IntrinsicShop = 24,
	MiniEvent = 25,
	CharacterStory = 26,
	MiniEventShop = 27,
	Sellout = 28,
	StemMap = 29,
	StemPreloadedMap = 30,
	CustomConversationData = 31,
	MainFieldItems = 32,
	Currencies = 33,
	BannerBackground = 34,
	DateIcon = 35,
	DateBackground = 36,
	PresentsIcons = 37,
	DateStory = 38,
	DateSounds = 39,
	MiniEventBackground = 40,
	OfferBackground = 41
}
