namespace GreenT.Steam.Achievements;

public class AchievementProvider
{
	public AchievementDTO[] Collection = new AchievementDTO[60]
	{
		new AchievementDTO(AchievementIdType.ACH_FINISH_TUTORIAL, "Horny graduate", "Take the training"),
		new AchievementDTO(AchievementIdType.ACH_FINISH_FIRST_ROOM, "Welcome to the Villa", "Entrance hall"),
		new AchievementDTO(AchievementIdType.ACH_FINISH_SWIMMING_POOL_ROOM, "Wet lover", "Swimming pool"),
		new AchievementDTO(AchievementIdType.ACH_FINISH_LIVING_ROOM, "Let there be light!", "Living room"),
		new AchievementDTO(AchievementIdType.ACH_FINISH_CASINO_ROOM, "You're gonna get lucky", "Casino"),
		new AchievementDTO(AchievementIdType.ACH_FINISH_CHILL_ZONE_ROOM, "I got the fire!", "Chill Zone"),
		new AchievementDTO(AchievementIdType.ACH_FINISH_DANCE_FLOOR_ROOM, "Disco dancer", "Dance Floor"),
		new AchievementDTO(AchievementIdType.ACH_FINISH_PARTY_ROOM, "Party king", "Party"),
		new AchievementDTO(AchievementIdType.ACH_FINISH_BAR_ROOM, "Bartender", "Bar"),
		new AchievementDTO(AchievementIdType.ACH_FINISH_TV_ROOM, "Cable lover", "TV"),
		new AchievementDTO(AchievementIdType.ACH_PROMOTE_ANY_TO_3, "Yeah, I'm the director", "Promote a girl up to level 3"),
		new AchievementDTO(AchievementIdType.ACH_PROMOTE_ANY_TO_5, "I'll make you a star", "Promote a girl up to level 5"),
		new AchievementDTO(AchievementIdType.ACH_PROMOTE_ANY_TO_10, "Talent Forge", "Promote a girl up to level 10"),
		new AchievementDTO(AchievementIdType.ACH_PROMOTE_ANY_TO_15, "She'll be grateful", "Promote a girl up to level 15"),
		new AchievementDTO(AchievementIdType.ACH_PROMOTE_ANY_TO_20, "Horny producer", "Promote a girl up to level 20"),
		new AchievementDTO(AchievementIdType.ACH_PROMOTE_ANY_TO_25, "Now you're pumped", "Promote a girl up to level 25"),
		new AchievementDTO(AchievementIdType.ACH_PROMOTE_ANY_TO_30, "Greatest producer", "Promote a girl up to level 30"),
		new AchievementDTO(AchievementIdType.ACH_GIRL_IN_COLLECTION_3, "To new heights!", "Get 3 girls in the collection"),
		new AchievementDTO(AchievementIdType.ACH_GIRL_IN_COLLECTION_5, "All the best for me!", "Get 5 girls in the collection"),
		new AchievementDTO(AchievementIdType.ACH_GIRL_IN_COLLECTION_10, "Great taste", "Get 10 girls in the collection"),
		new AchievementDTO(AchievementIdType.ACH_GIRL_IN_COLLECTION_15, "The bigger the better", "Get 15 girls in the collection"),
		new AchievementDTO(AchievementIdType.ACH_GIRL_IN_COLLECTION_20, "Insatiable collector", "Get 20 girls in the collection"),
		new AchievementDTO(AchievementIdType.ACH_GIRL_IN_COLLECTION_25, "Master of new positions", "Get 25 girls in the collection"),
		new AchievementDTO(AchievementIdType.ACH_GIRL_IN_COLLECTION_30, "More, I need more!", "Get 30 girls in the collection"),
		new AchievementDTO(AchievementIdType.ACH_GIRL_IN_COLLECTION_35, "True connoisseur", "Get 35 girls in the collection"),
		new AchievementDTO(AchievementIdType.ACH_GIRL_IN_COLLECTION_40, "That's a new record!", "Get 40 girls to collect"),
		new AchievementDTO(AchievementIdType.ACH_COMPLETE_CHAT_1, "Big talker", "Close dialog with 1 girl"),
		new AchievementDTO(AchievementIdType.ACH_COMPLETE_CHAT_3, "Master of correspondence", "Close dialog with 3 girls"),
		new AchievementDTO(AchievementIdType.ACH_COMPLETE_CHAT_5, "Genius of words", "Close dialog with 5 girls"),
		new AchievementDTO(AchievementIdType.ACH_COMPLETE_CHAT_8, "Master of dirty talk", "Close dialog with 8 girls"),
		new AchievementDTO(AchievementIdType.ACH_COMPLETE_CHAT_10, "Great negotiator", "Close dialog with 10 girls"),
		new AchievementDTO(AchievementIdType.ACH_COMPLETE_CHAT_15, "You're Shakespeare!", "Close dialog with 15 girls"),
		new AchievementDTO(AchievementIdType.ACH_COMPLETE_CHAT_20, "Lusty seducer", "Close dialog with 20 girls"),
		new AchievementDTO(AchievementIdType.ACH_COMPLETE_CHAT_25, "Your fingers know what to do", "Close dialog with 25 girls"),
		new AchievementDTO(AchievementIdType.ACH_COMPLETE_CHAT_30, "Sweet words", "Close dialog with 30 girls"),
		new AchievementDTO(AchievementIdType.ACH_COMPLETE_CHAT_35, "Dirty poet", "Close dialog with 35 girls"),
		new AchievementDTO(AchievementIdType.ACH_COMPLETE_CHAT_40, "The great romantic", "Close dialog with 40 girls"),
		new AchievementDTO(AchievementIdType.ACH_MERGE_100, "You've got talent!", "Merge items 100 times"),
		new AchievementDTO(AchievementIdType.ACH_MERGE_300, "You know what to do", "Merge items 300 times"),
		new AchievementDTO(AchievementIdType.ACH_MERGE_800, "Look what he's doing!", "Merge items 800 times"),
		new AchievementDTO(AchievementIdType.ACH_MERGE_1000, "You're good!", "Merge items 1000 times"),
		new AchievementDTO(AchievementIdType.ACH_MERGE_1500, "You did it!", "Merge items 1500 times"),
		new AchievementDTO(AchievementIdType.ACH_MERGE_1800, "IQ 999", "Merge items 1800 times"),
		new AchievementDTO(AchievementIdType.ACH_MERGE_2000, "I always win", "Merge items 2000 times"),
		new AchievementDTO(AchievementIdType.ACH_MERGE_2100, "I'm lucky today!", "Merge items 2100 times"),
		new AchievementDTO(AchievementIdType.ACH_MERGE_2300, "King of the villa!", "Merge items 2300 times"),
		new AchievementDTO(AchievementIdType.ACH_MERGE_2500, "Is there anything harder?", "Merge items 2500 times"),
		new AchievementDTO(AchievementIdType.ACH_MERGE_2800, "Rain Man", "Merge items 2800 times"),
		new AchievementDTO(AchievementIdType.ACH_MERGE_3000, "Game Master", "Merge items 3000 times"),
		new AchievementDTO(AchievementIdType.ACH_COLLECT_COMPANY_DARK, "Dark Side", "Gather the dark company"),
		new AchievementDTO(AchievementIdType.ACH_COLLECT_COMPANY_SCENE_LOVERS, "Hurry up on stage!", "Collect the scene lovers"),
		new AchievementDTO(AchievementIdType.ACH_COLLECT_COMPANY_INTERNET_STAR, "Internet star", "Collect internet stars"),
		new AchievementDTO(AchievementIdType.ACH_COLLECT_COMPANY_HOMEMAKERS, "Handyman", "Collect homemakers"),
		new AchievementDTO(AchievementIdType.ACH_COLLECT_COMPANY_REAL_HERO, "A real hero", "Collect super heroines"),
		new AchievementDTO(AchievementIdType.ACH_COLLECT_COMPANY_FAIRY_TALE, "Fairy tale lover", "Collect princesses"),
		new AchievementDTO(AchievementIdType.ACH_COLLECT_COMPANY_ASIA, "Horny east", "Collect your Asia"),
		new AchievementDTO(AchievementIdType.ACH_COLLECT_COMPANY_SPACE_CONQUEROR, "Space conqueror", "Get your space company"),
		new AchievementDTO(AchievementIdType.ACH_COLLECT_COMPANY_BAD_GIRLS, "Bad girl lover", "Collect bad girls"),
		new AchievementDTO(AchievementIdType.ACH_COLLECT_COMPANY_SUPERVILLAIN, "Supervillain", "Collect super villains"),
		new AchievementDTO(AchievementIdType.ACH_GET_ALL_EVENT_REWARDS, "The best of the best!", "Collect all the rewards in the event")
	};
}
